// Time constants in milliseconds
export const MILLISECONDS_PER_SECOND = 1000;
export const MILLISECONDS_PER_MINUTE = 60 * MILLISECONDS_PER_SECOND;
export const MILLISECONDS_PER_HOUR = 60 * MILLISECONDS_PER_MINUTE;
export const MILLISECONDS_PER_DAY = 24 * MILLISECONDS_PER_HOUR;
export const MILLISECONDS_PER_YEAR = 365 * MILLISECONDS_PER_DAY;

// Common time periods
export const SEVEN_DAYS = 7 * MILLISECONDS_PER_DAY;
export const FOURTEEN_DAYS = 14 * MILLISECONDS_PER_DAY;
export const THIRTY_DAYS = 30 * MILLISECONDS_PER_DAY;
export const SIXTY_DAYS = 60 * MILLISECONDS_PER_DAY; 